### ISSUE TITLE
Getting error while installing thrift@0.10 ventura 13.0

### ISSUE THREAD

**Issue by asifrahiman** [cartman-kai/homebrew-thrift#2]
==> Fetching cartman-kai/thrift/thrift@0.10
Error: thrift@0.10: Failed to download resource "thrift@0.10"
Failure while executing; `/usr/bin/env /opt/homebrew/Library/Homebrew/shims/shared/curl --disable --cookie /dev/null --globoff --show-error --user-agent Homebrew/4.0.19-24-ge96fd24\ \(Macintosh\;\ arm64\ Mac\ OS\ X\ 13.0\)\ curl/7.84.0 --header Accept-Language:\ en --retry 3 --fail --location --silent --head --request GET https://dlcdn.apache.org/thrift/0.10.0/thrift-0.10.0.tar.gz` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404
HTTP/2 404 
server: Apache
content-type: text/html; charset=iso-8859-1
via: 1.1 varnish, 1.1 varnish
accept-ranges: bytes
date: Fri, 26 May 2023 15:16:24 GMT
age: 359
x-served-by: cache-hel1410028-HEL, cache-maa10237-MAA
x-cache: HIT, HIT
x-cache-hits: 1, 1
x-timer: S1685114184.423323,VS0,VE1
content-length: 196

**Comment by cartman-kai** [comment]
Fixed #3 

Thank you for your feedback.  Please update your local brew tap and install Thrift. 

example:

```shell
$ brew update -v
$ brew install thrift@0.10
```
