### ISSUE TITLE
thrift@0.11 url 404

### ISSUE THREAD

**Issue by SwithinHwong** [cartman-kai/homebrew-thrift#5]
尝试安装thrift@0.11时报错，应该是thrift@0.11的URL需要修改

==> Fetching cartman-kai/thrift/thrift@0.11
==> Downloading https://archive.apache.org/dist/thrift/0.10.0/thrift-0.11.0.tar.gz
curl: (22) The requested URL returned error: 404

Error: thrift@0.11: Failed to download resource "thrift@0.11"
Download failed: https://archive.apache.org/dist/thrift/0.10.0/thrift-0.11.0.tar.gz

似乎URL从“https://archive.apache.org/dist/thrift/0.10.0/thrift-0.11.0.tar.gz” 修改为 “https://archive.apache.org/dist/thrift/0.11.0/thrift-0.11.0.tar.gz”就行

**Comment by cartman-kai** [comment]
#6 fixed
